# .goreleaser.yaml
builds:
  - binary: megophone
    env:
    - CGO_ENABLED=0
    ldflags:
    - -X cmd.Version={{.Version}}

aurs:
  - name: megophone-bin
    homepage: "https://github.com/coolapso/megophone"
    description: "post to multiple social networks simultaneously from your CLI"
    maintainers:
      - "coolapso <coolapso@coolapso.tech>"

    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/megophone-bin.git"
    skip_upload: auto

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

announce:
  discord:
    enabled: true
