name: Release
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  tests:
    uses: coolapso/megophone/.github/workflows/test.yaml@main

  release:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
